apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    nfs: jenkins
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /rootfs_jenkins
    server: 192.168.1.142